### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by udhayakumarth** [saivigneesh456/Predic-_Cons_Sen#2]
Hi vigneesh,

I'm udhayakumar, sorry to disturb you. I need your help in virtusa project phase.

Springboot app and React app  stater files are not give in examly portal. we have to create those?

Thanks in advance.

**Comment by saivigneesh456** [comment]
No it automatically  will create

**Comment by udhayakumarth** [comment]
I have already initiated the spring app and react app!!

[This is my WhatsApp number ](https:/api.whatsapp.com/send?phone=+916381173167) 

We didn't get the mentor still. If you don't mind please text me in what's app and tell me about how you're doing your project.

**Comment by saivigneesh456** [comment]
What you are saying I didnt get you
I cant find your number
